// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/GlebMoskalev/chat-golang/internal/service (interfaces: ChatServiceInterface)
//
// Generated by this command:
//
//	mockgen -destination=internal/service/mocks/mock_chat_service.go -package=mocks github.com/GlebMoskalev/chat-golang/internal/service ChatServiceInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/GlebMoskalev/chat-golang/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockChatServiceInterface is a mock of ChatServiceInterface interface.
type MockChatServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockChatServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockChatServiceInterfaceMockRecorder is the mock recorder for MockChatServiceInterface.
type MockChatServiceInterfaceMockRecorder struct {
	mock *MockChatServiceInterface
}

// NewMockChatServiceInterface creates a new mock instance.
func NewMockChatServiceInterface(ctrl *gomock.Controller) *MockChatServiceInterface {
	mock := &MockChatServiceInterface{ctrl: ctrl}
	mock.recorder = &MockChatServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatServiceInterface) EXPECT() *MockChatServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateChat mocks base method.
func (m *MockChatServiceInterface) CreateChat(ctx context.Context, title string) (*models.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChat", ctx, title)
	ret0, _ := ret[0].(*models.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChat indicates an expected call of CreateChat.
func (mr *MockChatServiceInterfaceMockRecorder) CreateChat(ctx, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChat", reflect.TypeOf((*MockChatServiceInterface)(nil).CreateChat), ctx, title)
}

// CreateMessage mocks base method.
func (m *MockChatServiceInterface) CreateMessage(ctx context.Context, chatID int64, text string) (*models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMessage", ctx, chatID, text)
	ret0, _ := ret[0].(*models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMessage indicates an expected call of CreateMessage.
func (mr *MockChatServiceInterfaceMockRecorder) CreateMessage(ctx, chatID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessage", reflect.TypeOf((*MockChatServiceInterface)(nil).CreateMessage), ctx, chatID, text)
}

// DeleteChat mocks base method.
func (m *MockChatServiceInterface) DeleteChat(ctx context.Context, chatID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChat", ctx, chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChat indicates an expected call of DeleteChat.
func (mr *MockChatServiceInterfaceMockRecorder) DeleteChat(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChat", reflect.TypeOf((*MockChatServiceInterface)(nil).DeleteChat), ctx, chatID)
}

// GetChatWithMessages mocks base method.
func (m *MockChatServiceInterface) GetChatWithMessages(ctx context.Context, chatID int64, limit int) (*models.ChatWithMessages, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatWithMessages", ctx, chatID, limit)
	ret0, _ := ret[0].(*models.ChatWithMessages)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatWithMessages indicates an expected call of GetChatWithMessages.
func (mr *MockChatServiceInterfaceMockRecorder) GetChatWithMessages(ctx, chatID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatWithMessages", reflect.TypeOf((*MockChatServiceInterface)(nil).GetChatWithMessages), ctx, chatID, limit)
}
